# Generated by Django 5.2.7 on 2025-10-08 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('static', 'Static Website'), ('fullstack', 'Full-Stack Website')], max_length=20)),
                ('stack', models.CharField(choices=[('html_css_js', 'HTML/CSS/JavaScript'), ('react_node', 'React + Node.js'), ('vue_express', 'Vue + Express'), ('nextjs', 'Next.js Full-Stack'), ('django_react', 'Django + React')], max_length=50)),
                ('has_authentication', models.BooleanField(default=False)),
                ('has_database', models.BooleanField(default=False)),
                ('has_api', models.BooleanField(default=False)),
                ('has_realtime', models.BooleanField(default=False)),
                ('has_payments', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('generation_prompt', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='generator.project')),
            ],
            options={
                'verbose_name_plural': 'Generation histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('config', 'Configuration'), ('docs', 'Documentation')], max_length=20)),
                ('content', models.TextField()),
                ('language', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='generator.project')),
            ],
            options={
                'ordering': ['category', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('vercel', 'Vercel'), ('netlify', 'Netlify'), ('heroku', 'Heroku'), ('railway', 'Railway'), ('render', 'Render')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('deployment_logs', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='generator.project')),
            ],
        ),
    ]
